[BarClerk-944] - [Markup] Create court appearances page with modal
impaulintech/barclerk pull request #30
Opened 2022-12-01 10:27 UTC by jasonclchua

## Issue Link
- https://app.asana.com/0/1203234368773394/1203256371568944

## Note
- [ ] momentJS installed for dateTime to String conversion

## Definition of Done
- [ ] Add markup for Court Appearances page
  - [ ] Add `court appearance accordion`
  - [ ] Add `edit court appearance modal`
  - [ ] Add `add court appearance` modal

## Pre-condition
- 

## Expected Output
  - When user clicks `View More` on Client Profile page, they will be redirected to the Court Appearances page
  - When user clicks on the chevronDown icon on CourtAppearanceAccordion, the accordion body will appear
  - When user clicks on editIcon for a CourtAppearanceAccordion, the editCourtAppearance Modal appears with the provided data (form submission to be added on FE Integration)
  - When the user clicks `Add Court Appearance` on the header, the AddCourtAppearance modal appears.
  - Pagination is added. Maximum of 5 items are visible per page.

## Screenshots/Recordings
<img width="1290" alt="image" src="https://user-images.githubusercontent.com/118783823/205028991-aefb03f5-af59-4622-9039-cc33fc594eba.png">
<img width="914" alt="image" src="https://user-images.githubusercontent.com/118783823/205029034-ce830fb9-cea2-4e8f-aa5c-f4a34ce52f09.png">
<img width="894" alt="image" src="https://user-images.githubusercontent.com/118783823/205029080-e3b78762-cc77-47c8-8759-d6f03ce2e87c.png">

2022-12-01 12:39 UTC, abduljalilpalala commented on client/src/components/molecules/CourtAppearanceAccordion/EditCourtAppearanceModal.tsx
> +
Sort out imports.

```suggestion
import { useForm } from 'react-hook-form'
import { Dialog } from '@headlessui/react'
import React, { FC, useEffect, useState } from 'react'
import TextareaAutosize from 'react-textarea-autosize'
import { HiOutlineOfficeBuilding } from 'react-icons/hi'
import { Calendar, Clock, Columns, Edit, Plus, User, X } from 'react-feather'

import { Spinner } from '~/shared/icons/SpinnerIcon'
import { ICourtAppearance } from '~/shared/interfaces'
import { yupResolver } from '@hookform/resolvers/yup'
import DialogBox from '~/components/templates/DialogBox'
import { CourtAppearanceFormValues } from '~/shared/types'
import { CourtAppearanceSchema } from '~/shared/validation'
import CourtChargesIcon from '~/shared/icons/CourtChargeIcon'
```

2022-12-01 12:39 UTC, abduljalilpalala commented on client/src/components/molecules/CourtAppearanceAccordion/EditCourtAppearanceModal.tsx
> +export default EditCourtAppearanceModal
Add new line

2022-12-01 12:40 UTC, abduljalilpalala commented on client/src/components/molecules/CourtAppearanceAccordion/index.tsx
> +}): JSX.Element => {
Add proper types instead of `any`

2022-12-01 12:41 UTC, abduljalilpalala commented on client/src/components/molecules/CourtAppearanceList/AddNewCourtAppearance.tsx
> +
Sort out imports.

```suggestion
import { useForm } from 'react-hook-form'
import { Dialog } from '@headlessui/react'
import React, { FC, useEffect, useState } from 'react'
import TextareaAutosize from 'react-textarea-autosize'
import { HiOutlineOfficeBuilding } from 'react-icons/hi'
import { yupResolver } from '@hookform/resolvers/yup'
import { Calendar, Clock, Edit, Plus, User, X } from 'react-feather'

import { Spinner } from '~/shared/icons/SpinnerIcon'
import DialogBox from '~/components/templates/DialogBox'
import CourtChargesIcon from '~/shared/icons/CourtChargeIcon'
import { CourtAppearanceFormValues } from '~/shared/types'
import { CourtAppearanceSchema } from '~/shared/validation'


```

2022-12-01 12:42 UTC, abduljalilpalala commented on client/src/components/molecules/CourtAppearanceList/AddNewCourtAppearance.tsx
> +  // }, [isOpen])
If the comment is needed, add TODO: on to it or else remove the comment

2022-12-01 12:43 UTC, abduljalilpalala commented on client/src/components/molecules/CourtAppearanceList/index.tsx
> +
```suggestion
import { useState } from 'react'
import ReactPaginate from 'react-paginate'

import CourtAppearanceAccordion from '../CourtAppearanceAccordion'
import { ICourtAppearance } from '~/shared/interfaces'

```

2022-12-01 12:44 UTC, abduljalilpalala requested changes
Please check comments.

2022-12-01 13:23 UTC, jsvelte approved these changes
# Approved 💯

2022-12-04 06:08 UTC, abduljalilpalala commented on client/src/hooks/useCourtAppearance.ts
> +}
Add new line

2022-12-04 06:09 UTC, abduljalilpalala commented on client/src/pages/matter/[id]/court-appearances.tsx
> +import { Plus } from 'react-feather'
Move this import at the top

2022-12-04 06:11 UTC, abduljalilpalala requested changes
Minor comment, please check.

2022-12-04 06:13 UTC, jasonclchua commented
> Minor comment, please check.

comment resolved.

2022-12-04 06:58 UTC, abduljalilpalala approved these changes
### Approved! ✔️

2022-12-04 06:58 UTC, merged