[BarClerk-948] - [FE] Integrate Get all clients/matter info in profil…
impaulintech/barclerk pull request #36
Opened 2022-12-07 05:57 UTC by jasonclchua

## Issue Link
- https://app.asana.com/0/1203234368773394/1203256371568948

## Definition of Done
- [ ] integrate client data in Client Profile page. Includes the ff:
  - [ ] client profile information - contribution, bail status, court, location, list of charges
  - [ ] client court appearances
  - [ ] client extensions
  - [ ] client funds information

## Pre-condition
- [ ] create sample client
- [ ] create GOL data and courtAppearances data for client

## Expected Output
  - [ ] when the user opens a client record from Dashboard Page, they will be redirected to the client's profile.
  - [ ] if client has extensions available, when user clicks on the client_extension dropdown, it will show the list of available extensions. Otherwise, if the client has no client_extension, 'no available data' message is shown on the dropdown. The client's funds are shown based on active client_extension from the dropdown. 
  - [ ] the client's court_appearances data are shown on the right portion of the page. If there are no court_appearances available for the client, 'no data available' message is shown instead.

## Screenshots/Recordings
<img width="1059" alt="image" src="https://user-images.githubusercontent.com/118783823/206099904-66a38a56-c0de-4cf1-93d9-cbad47ce73b1.png">
<img width="1062" alt="image" src="https://user-images.githubusercontent.com/118783823/206099545-f128b960-7709-4675-8d0a-0b1e1c39dbdf.png">
<img width="1062" alt="image" src="https://user-images.githubusercontent.com/118783823/206099748-0746de0a-ed39-43e6-8159-4251d683e27f.png">

2022-12-07 07:12 UTC, impaulintech requested changes

2022-12-07 07:12 UTC, impaulintech commented on client/src/redux/client-profile/clientProfileSlice.ts
> +export default clientProfile.reducer
Add new line

2022-12-07 14:04 UTC, jsvelte reviewed
Please add custom skeleton loading style on initial load for reference please view this link: https://flowbite.com/docs/components/skeleton/ . Thank you

2022-12-07 23:11 UTC, abduljalilpalala commented on client/src/redux/client-profile/clientProfileSlice.ts
> +  allClientExtensions: any
Add it's proper types instead of `any`

2022-12-07 23:12 UTC, abduljalilpalala requested changes
I left some comments. Please check.

2022-12-08 00:19 UTC, impaulintech approved these changes
Resolve sir AJ's comment other than that, I approve.

2022-12-08 04:18 UTC, jsvelte approved these changes
# Approved 💯

2022-12-08 14:05 UTC, abduljalilpalala approved these changes

2022-12-09 03:40 UTC, merged